### ISSUE TITLE
必要なGemをインストールする

### ISSUE THREAD

**Issue by KanameEndo** [KanameEndo/Small-Farm#1]
必要なGemをインストールする

**Comment by KanameEndo** [comment]
必要なGemインストール完了OK

**Comment by tadao050707** [comment]
完了したIssueは、クローズしていきましょう。

<img width="340" alt="スクリーンショット 2022-08-06 16 16 21" src="https://user-images.githubusercontent.com/24279672/183238887-454052cb-eab2-4e04-aa06-30996eb19373.png">
