### ISSUE TITLE
報告事項

### ISSUE THREAD

**Issue by KanameEndo** [KanameEndo/Small-Farm#9]

**Comment by KanameEndo** [comment]
テーブル定義において数点変更のご報告です。

①フードテーブル
　・カラム名変更
　　商品画像をiconからimageにしました。
　　理由：商品の画像ですので、iconでは適切ではないからです。
　・データ型変更
　　税込価格をintegerにしていましたが、stringへ変更しました。
　　理由：商品のグラム数によって　例）100円〜200円と表記したいからです。

②管理者スケジュールテーブル
　・テーブル名変更
　　admin_plansにしてましたがplansに変更しました。
　　理由：このアプリにはスケジュールテーブルは一つしかないためadminは不要です。
　・カラム名変更
　　日程がscheduleでしたが、start_timeへ変更しました。
　　このgemではstart_timeとend_timeの定義が必要でした。
　　実際に試したところエラーが出て原因を調べたところ、このカラムにする必要がありました。

以上、よろしくお願いいたします。

**Comment by tadao050707** [comment]
遠藤さん、変更の件、承知しました。
今後は「変更して良いですか」という方針でお願いいたします。

**Comment by KanameEndo** [comment]
【テーブル追加 ご許可のお願い】
お問合せフォーム実装するために下記記事を参考にしようと思っております。

https://qiita.com/japwork/items/145645e281b81d9bf92c

問い合わせフォーム用にテーブルが必要になってくるのですが、
追加してもよろしいでしょうか。

●テーブル名
　contacts
○データ型：カラム名
　string :name
　string :email
　string :phone_number
　integer :subject
　text :message

私の下調べが不足しておりました。
ご確認のほど、よろしくお願いいたします。

**Comment by KanameEndo** [comment]
mentor 【メンター】小林忠雄 22/08/13 08:12
遠藤さん、お疲れ様です。

テーブル追加の件、承知しました！進めてください！

**Comment by KanameEndo** [comment]
度々の変更のご相談になり、すみません。
画像アップロードにActive Storageを使用したいです。
そのためActive Storageで必要になってくるテーブルを追加したいです。
万葉課題で購入した「Ruby on Rails 速習実践ガイド」にActive Storageの項目があり、
（逆にテキストで紹介されているCarryWaveがない）もしかしたら、
現場ではこちらを導入しているところが多いと思い、
実際に就職した時のことと、いずれにしてもスクールで質問できる間に挑戦してみたいと思いました。
AWSが必須になりますが、どうぞご許可のほど、
よろしくお願いいたします。

**Comment by KanameEndo** [comment]
mentor 【メンター】小林忠雄 22/08/13 12:39
遠藤さん、承知しました！
Active Storageは現場でよく使われております！
進めてください！

**Comment by KanameEndo** [comment]
8/27合格判定をいただいたためクローズ
